// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: DeleteFeedFollows.sql

package database

import (
	"context"
)

const deleteFeedFollows = `-- name: DeleteFeedFollows :exec
DELETE FROM feed_follows
`

func (q *Queries) DeleteFeedFollows(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollows)
	return err
}
