// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: DeleteFollowForUser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFollowsForUser = `-- name: DeleteFollowsForUser :exec
DELETE FROM feed_follows
WHERE user_id = $1
  AND feed_id = $2
`

type DeleteFollowsForUserParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeleteFollowsForUser(ctx context.Context, arg DeleteFollowsForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollowsForUser, arg.UserID, arg.FeedID)
	return err
}
