// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetUser.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one
select name from users
where name = $1
`

func (q *Queries) GetUser(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUser, name)
	err := row.Scan(&name)
	return name, err
}
